AllCops:
  TargetRubyVersion: 2.6

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/HashAlignment:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/SuppressedException:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 2

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Metrics/AbcSize:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    map: "collect"
    reduce: "inject"
    find: "detect"
    find_all: "select"

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/AsciiComments:
  Enabled: false
